name: .NET Build & Archive
on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build Debug
        run: dotnet build --configuration Debug --no-restore
      - name: Build Release
        run: dotnet build --configuration Release --no-restore
      - name: Upload Debug Binary
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-debug-binaries
          path: bin/Debug/
          if-no-files-found: error
      - name: Upload Release Binary
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-release-binaries
          path: bin/Release/
          if-no-files-found: error