name: .NET Build & Archive
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup .NET
        run: |
          apt-get update && apt-get install -y wget
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel 8.0 # Change to your version (6.0, 7.0, etc)
          echo "$HOME/.dotnet" >> $GITHUB_PATH
          echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build Debug
        run: dotnet build --configuration Debug --no-restore
      - name: Build Release
        run: dotnet build --configuration Release --no-restore
      - name: Upload Debug Binary
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-debug-binaries
          path: bin/Debug/
          if-no-files-found: error
      - name: Upload Release Binary
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-release-binaries
          path: bin/Release/
          if-no-files-found: error