name: Security Scan
on: 
  push:
    branches: [main, master]
  pull_request:
  schedule:
    - cron: '0 9 * * 1'

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js for Actions
        run: |
          apt-get update
          apt-get install -y curl
          curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
          apt-get install -y nodejs
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Check for vulnerable packages
        run: dotnet list package --vulnerable --include-transitive
      - name: Check for deprecated packages
        run: dotnet list package --deprecated